
name: Create release
on: 
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: 'Version number Eg: 4.2.0' 

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@neutralinojs'
      
    - name: Configure
      run: |
        npm ci
        
    - name: Add, Commit and Push Release Zip
      uses: EndBug/add-and-commit@v7.4.0
      with:
        default_author: github_actions
        message: 'Add v${{github.event.inputs.version}} pre-built x64 binaries to release zip' 
        add: './bin/neutralinojs-v${{github.event.inputs.version}}.zip'
        
    - name: Create Release Notes
      run: |
        chmod +x ./scripts/rz.py
        ./scripts/rz.py create ${{github.event.inputs.version}}
        
    - name: Commit and Push Changelog
      uses: EndBug/add-and-commit@v7.4.0
      with:
        default_author: github_actions
        message: 'Update changelog for v${{github.event.inputs.version}}' 
        add: 'CHANGELOG.md'
        tag: v${{github.event.inputs.version}}
        
    - name: Create Branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      with: 
        branch: v${{github.event.inputs.version}}
      env:
        GITHUB_TOKEN: ${{ secrets.BRANCH_TOKEN }}
        
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
          tag: v${{github.event.inputs.version}}
          name: Neutralinojs CLI v${{github.event.inputs.version}} released!
          bodyFile: ./.tmprz/release_notes.md
          draft: true
          
    - name: Configure
      run: |
        npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
    - name: Clean Release Notes
      run: |
        ./scripts/rz.py cleanup
