name: Test suite

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        arch: [x64]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install neu & link it
      working-directory: ./
      run: |
        npm ci
        npm link

    - name: Run Spec
      working-directory: ./spec
      run: |
        npm ci
        npm run test
